services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  app:
    build: .
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      NODE_ENV: development
      API_KEY: ABCDEFGHIJKLMNOPQRSTUWXYZ
volumes:
  mongo: {}