services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  app:
    build: .
    stdin_open: true 
    tty: true        
    depends_on:
      - mongo
    environment:
      MONGODB_URL_0: mongodb://root:example@mongo
      NODE_ENV: development
      API_KEY: YOUR_API_KEY_HERE
volumes:
  mongo: {}